[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture"

[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENV = "production"
  
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; img-src 'self' https:;"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
